### ISSUE TITLE
在NSPopover的contentViewController中无法正常使用

### ISSUE THREAD

**Issue by iptodays** [IsaacXen/IXRefreshableScrollView#3] opened 2019-04-11 07:59 UTC
![image](https://user-images.githubusercontent.com/15830996/55940424-af626880-5c72-11e9-930d-a19847d1e782.png)

**Comment by IsaacXen** [comment] 2019-04-11 09:32
I was unable to reproduce your issue.

Provide critical steps to reproduce, or consider making a demo that can reproduce the issue.

**Comment by iptodays** [comment] 2019-04-12 01:20
[demo.zip](https://github.com/IsaacXen/IXRefreshableScrollView/files/3071205/demo.zip)

I make a demo, this demo reproduce question

**Comment by IsaacXen** [comment] 2019-04-12 05:05
Thanks for taking time to make a demo project.

The problem is, IXScrollView add its supplementary view constraints during initialization where its document view could be nil, which is not allowed in Auto Layout.

A fix that delay this process had been committed. Pull it and replace the old one you have, it should work now.

**Closed as completed** 2019-04-12 05:08 UTC
Labels: bug
